# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: ci

on:
  push:
    branches: "*"
  pull_request:
    branches: "main"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: "checkout repository"
      uses: actions/checkout@v4
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        cache-dependency-path: '/home/runner/work/footnote/footnote/footnote-backend'
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: "Create SSL certificate file"
      run: |
        echo "${{ secrets.DB_SSL__CA }}" | base64 -d > /home/runner/work/footnote/footnote/footnote-backend/config/ca-certificate.crt


    - name: "Create .env file"
      run: |
        echo "DB_HOST=${{ secrets.DB_HOST }}" >> /home/runner/work/footnote/footnote/footnote-backend/.env
        echo "DB_USER=${{ secrets.DB_USER }}" >> /home/runner/work/footnote/footnote/footnote-backend/.env
        echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> /home/runner/work/footnote/footnote/footnote-backend/.env
        echo "DB_DATABASE=${{ secrets.DB_DATABASE }}" >> /home/runner/work/footnote/footnote/footnote-backend/.env
        echo "DB_PORT=${{ secrets.DB_PORT }}" >> /home/runner/work/footnote/footnote/footnote-backend/.env
        echo "DB_SSL__CA=config/ca-certificate.crt" >> /home/runner/work/footnote/footnote/footnote-backend/.env
        echo "SESSION_SECRET=${{ secrets.SESSION_SECRET }}" >> /home/runner/work/footnote/footnote/footnote-backend/.env
        echo "DO_SPACES_ENDPOINT=${{ secrets.DO_SPACES_ENDPOINT }}" >> /home/runner/work/footnote/footnote/footnote-backend/.env
        echo "DO_SPACES_KEY=${{ secrets.DO_SPACES_KEY }}" >> /home/runner/work/footnote/footnote/footnote-backend/.env
        echo "DO_SPACES_SECRET=${{ secrets.DO_SPACES_SECRET }}" >> /home/runner/work/footnote/footnote/footnote-backend/.env
        echo "DO_SPACES_BUCKET=${{ secrets.DO_SPACES_BUCKET }}" >> /home/runner/work/footnote/footnote/footnote-backend/.env

    - name: "Install dependencies"
      working-directory: '/home/runner/work/footnote/footnote/footnote-backend'  
      run: npm ci
    - name: "Build project"
      working-directory: '/home/runner/work/footnote/footnote/footnote-backend'
      run: npm run build --if-present
    - name: "Run tests"
      working-directory: '/home/runner/work/footnote/footnote/footnote-backend'
      run: npm test
